spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/test
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    change-log: classpath:changelog.yaml

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/test
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: my-group

      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

      properties:
        spring.json.trusted.packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

keycloak:
  server-url: http://localhost:8080
  realm: test
  client-id: test-client
  client-secret: test-secret

springdoc:
  swagger-ui:
    oauth:
      client-id: test-client
      client-secret: test-secret
      additional-query-string-params:
        prompt: login
outbox:
  cron: "0 */5 * * * *"

kafka:
  topics:
    output:
      storage-event: "storage.order.solutions"
    input: "storage.order.questions"
  events:
    input:
      creating-event: "OrderSentForApproval"

logging:
  level:
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE