spring.config.import=optional:file:.env[.properties]
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=dev
spring.datasource.password=THIsf-ISDFFf-rllyg342-difFFdacult-PASdfasdgWord
spring.datasource.url=jdbc:postgresql://localhost:55554/car_seller?sslmode=disable
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.liquibase.change-log=classpath:db/changelog/changelog.yaml
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:11222/realms/Oauth
#spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:11222/realms/Oauth/protocol/openid-connect/certs
keycloak.server-url=http://localhost:11222
keycloak.realm=Oauth
keycloak.client-id=admin-cli
keycloak.username=admin
keycloak.password=admin