spring:
  config:
    import: optional:file:.env[.properties]
  
  profiles:
    active: otel

  application:
    name: order

  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}?sslmode=disable

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  liquibase:
    change-log: classpath:db/changelog/changelog.yaml

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${KEYCLOAK_HOST}:${KEYCLOAK_PORT}/realms/${KEYCLOAK_REALM}
          jws-algorithms: RS256

  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: order-consumers

      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

      properties:
        spring.json.trusted.packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

grpc:
  client:
    storage-service:
      address: static://${STORAGE_GRPC_HOST}:${STORAGE_GRPC_PORT}
      negotiationType: plaintext

keycloak:
  server-url: http://${KEYCLOAK_HOST}:${KEYCLOAK_PORT}
  realm: ${KEYCLOAK_REALM}
  client-id: ${KEYCLOAK_CLIENT_ID}
  client-secret: ${KEYCLOAK_CLIENT_SECRET}

springdoc:
  swagger-ui:
    oauth:
      client-id: ${SPRINGDOC_SWAGGER_UI_OAUTH_CLIENT_ID}
      client-secret: ${SPRINGDOC_SWAGGER_UI_OAUTH_CLIENT_SECRET}
      additional-query-string-params:
        prompt: login

kafka:
  topics:
    output: "storage.order.questions"
    input: "storage.order.solutions"
  events:
    input:
      rejected: "OrderRejected"
      approved: "OrderApproved"
    output: "OrderSentForApproval"

outbox:
  cron: "*/5 * * * * *"

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG

kind: Spring Boot

management:
  tracing:
    sampling:
      probability: 1.0
    propagation:
      type:
        - W3C
        - B3
  otlp:
    tracing:
      endpoint: http://localhost:4318
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  metrics:
    export:
      prometheus:
        enabled: true
  endpoint:
    health:
      show-details: always