CREATE TABLE IF NOT EXISTS nodes (
    id BIGINT PRIMARY KEY GENERATED AS IDENTITY,
    name TEXT NOT NULL
)

CREATE TABLE IF NOT EXISTS car_parts (
    id BIGINT PRIMARY KEY GENERATED AS IDENTITY,
    name TEXT NOT NULL,
    node_id BIGINT REFERENCES nodes(id) NOT NULL
)