CREATE TABLE IF NOT EXISTS clients (
    id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY
)

CREATE TABLE IF NOT EXISTS composition_admins (
    id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY
)

CREATE TABLE IF NOT EXISTS managers (
    id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY
)

CREATE TABLE IF NOT EXISTS system_admins (
    id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY
)