FROM liquibase/liquibase:5.0

WORKDIR /app/liquibase-settings

RUN liquibase lpm add postgresql

COPY migrations /app/liquibase-settings/migrations/

COPY liquibase-settings /app/liquibase-settings 

ENTRYPOINT [ "/app/liquibase-settings/entrypoint.sh" ]