spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/test
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    change-log: classpath:db/changelog/changelog.yaml

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/test

keycloak:
  server-url: http://localhost:8080
  realm: test
  client-id: test-client
  client-secret: test-secret

springdoc:
  swagger-ui:
    oauth:
      client-id: test-client
      client-secret: test-secret
      additional-query-string-params:
        prompt: login

logging:
  level:
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE